### ISSUE TITLE
How I can paginate the result of a cypher query?

### ISSUE THREAD

**Issue by levidamian** [megorei/kaminari-neo4j#1]
Here is my controller method:
  def bisac_main_counts
    q = "
    MATCH (b:Bisac) WHERE (b.bisac_code =~ '.*000000')
    WITH b, size((b)<-[:INCLUDED_IN]-()) as wokas_count
    RETURN b.bisac_code as bisac_code, b.bisac_value as bisac_value, wokas_count
    ORDER BY b.bisac_code
    ;"
    @result = Neo4j::Session.current.query(q).page(params[:page]).per(5)
  end

When I am executing the code the error I am encountering is:
undefined method `page' for #<Enumerator: #<Enumerator::Generator:0x007fba536e7ae8>:each>

for the line:     @result = Neo4j::Session.current.query(q).page(params[:page]).per(5)

**Comment by levidamian** [comment]
Used these:
    @result = Neo4j::Session.current.query(q).to_a
    @result = Kaminari.paginate_array(@result).page(params[:page])

**Comment by andrewhavens** [comment]
The reason for the `undefined method "page"` is because you haven't actually loaded the gem. I was just bit by this as well. You need to add this line somewhere in your codebase:

```
require "kaminari/neo4j"
```

**Comment by levidamian** [comment]
I replaced kaminari with will_paginate.
Works better.
